describe('Positive dan Negative Test', () => {
  it('Positive test = Success login an account with valid data', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('[data-label="or"]').first().click()
    cy.get('#email').type('sibunavi@cyclelove.cc')
    cy.get('#pass').type('Demo1234')
    cy.get('#send2').first().click()
  })
  it('Negative test = failed to login due to wrong email', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('[data-label="or"]').first().click()
    cy.get('#email').type('febynihayatus@gmail.com')
    cy.get('#pass').type('Demo1234')
    cy.get('#send2').first().click()
    cy.get('.messages').should('contain', 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.')
  })
  it('Negative test = failed to login due to wrong password', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('[data-label="or"]').first().click()
    cy.get('#email').type('sibunavi@cyclelove.cc')
    cy.get('#pass').type('Demoaaaa')
    cy.get('#send2').first().click()
    cy.get('.messages').should('be.visible').and('contain', 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.')
  })
  it('Negative test = invalid email (not using @)', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('[data-label="or"]').first().click()
    cy.get('#email').type('sibunavicyclelove.cc')
    cy.get('#pass').type('Demoaaaa')
    cy.get('#email-error').should('contain', 'Please enter a valid email address (Ex: johndoe@domain.com).')
  })
  it('Negative test =Login fails if any of the fields are left blank.', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('[data-label="or"]').first().click()
    cy.get('#email').type('sibunavicyclelove.cc')
    cy.get('#send2').first().click()
    cy.get('#pass-error').should('contain', 'This is a required field.')
  })
})